variable "tier_nb" {
  description = "tier in which data lookups will be run: 1, 2 or 3"
  type = string
}

variable "metadata" {
  description = "Auto-generated values. Map of well known values passed by the automation itself: env_subtype external_segment, internal_segment, component, datacenter"
  type = map
}

variable "custom_userdata" {
  description = "custom_userdata or empty for nothing"
  default = ""
}

variable "counter" {
  description = "Number of instances to create"
  default = "1"
}

variable "ssh_pub_developer" {
  description = "Recommended: empty"
  default = ""
}

variable "additional_sg_ids" {
  description = "additional security groups"
  type = list
  default = []
}

variable "short_name" {
  description = "seed the name of the VM"
  default = "vm"
}

variable "custom_tags" {
  description = "Additional tags"
  type = map
  default = {}
}

variable "instance_type" {
  description = "Instance type. defaults to t2.micro"
  default = ""
}

variable "ami_name_regex" {
  description = "Regex to select the AMI to use"
  default = ""
}

variable "eip_enabled" {
  description = "True to associate an Elastic IP"
  default = "false"
}

variable "root_volume_size" {
  description = "Size in GB of the root volume"
  default = ""
}

variable "internal_domain_name" {
  description = "Auto generated by default"
  default = ""
}

variable "attach_labeled_volumes" {
  description = "When not empty, will attach to each instance an existing volume"
  default = ""
}

variable "sis_mount_vol_path" {
  description = "For the userdata. When set the /dev/vdb will be waited, formatted partitioned and mounted"
  default = ""
}

variable "data_volume_size" {
  description = "Size of the EBS attached to the instance"
  default = "10"
}

variable "data_volume_type" {
  description = "Type of the EBS attached to the instance"
  default = "gp2"
}

variable "data_device_name" {
  description = "Device name to use in attaching the EBS"
  default = "/dev/vdb"
}

variable "data_volume_enabled" {
  description = "Flag to enable additional EBS to instance"
  default = "0"
}

